### ISSUE TITLE
Demo App forgets configuration

### ISSUE THREAD

**Issue by SirColeslaw** [SasaKaranovic/VU-Demo-App#3] opened 2024-01-13 07:39 UTC
Hello, I have noticed that the demo app forgets my dial configuration every time I start it. Now the question is, is the demo app intended to be used permanently or is it really more of a demo, in the sense of: "This is what your own app could look like". Because basically, the demo app already offers me everything I currently need. At least until AIDA64 support comes, and I could then get the data from there.

**Comment by Famku** [comment] 2024-01-13 16:32
I have the same issue

**Comment by SasaKaranovic** [comment] 2024-01-14 08:36
Can you please try deleting `VU1-DemoApp` folder that is located at `c:\Users\[YOUR_USERNAME]\KaranovicResearch` and re-start the VU1 Demo application.

Please make sure you are running the latest version of the Demo App. You can download the latest version from https://vudials.com/download/demo_app (At the time of writing this, latest version is `v240114`)

> Now the question is, is the demo app intended to be used permanently or is it really more of a demo, in the sense of: "This is what your own app could look like".

That is a great question. The idea is that this application is a demo that demonstrates how you could use your VU dials for PC resource usage monitoring as well as demoing main features of the dial (setting background image, setting backlight and the dial value). But at the same time we don't want to build competing software packages (better explained in [VU Server readme](https://github.com/SasaKaranovic/VU-Server#why-not-build-apps-for-vu-dials)).

> Because basically, the demo app already offers me everything I currently need. At least until AIDA64 support comes, and I could then get the data from there.

This is exactly the idea for the VU1 Demo app. Make a functional application to bridge the gap until support for VU dials start coming in popular software packages. We strongly believe that integrating VU dials into existing software packages is relatively easy. VU Dials API is open-source and documented (https://docs.vudials.com).

If you wish to help, you can ask the developers of your favorite software packages to add support for VU dials.

**Comment by SirColeslaw** [comment] 2024-01-16 15:39
Well, I tried that, i.e. deleting the folder, but unfortunately, it didn't work. I also downloaded the latest version, but unfortunately that didn't help either. Could it have something to do with the user I am logged in as, I always work with the local administrator.

**Comment by Famku** [comment] 2024-01-16 16:57
vu1demo_config.yaml reset every time the demo is started.

**Comment by SasaKaranovic** [comment] 2024-01-17 05:02
Can you please post your `vu1demo_config.yaml` so I can take a look at it?

Also can you open http://localhost:5340/api/v0/dial/list?key=cTpAWYuRpA2zx75Yh961Cg in your browser and paste here the complete output.

Is it possible that your dial name(s) maybe contain special characters?

**Comment by Famku** [comment] 2024-01-17 05:07
vu1demo_config.yaml

```yaml
dial_metrics: []
dial_update_period: 0.5
master_key: cTpAWYuRpA2zx75Yh961Cg

pu/0/load/0
  scaling_min: 0
  scaling_max: 100
  thresholds: []
dial_update_period: 0.5
master_key: cTpAWYuRpA2zx75Yh961Cg

_key: cTpAWYuRpA2zx75Yh961Cg
```

http://localhost:5340/api/v0/dial/list?key=cTpAWYuRpA2zx75Yh961Cg

```json
{"status": "ok", "message": "", "data": [{"uid": "380032000650564139323920", "dial_name": "HUB", "value": 0, "backlight": {"red": 0, "green": 0, "blue": 0}, "image_file": "img_380032000650564139323920"}]}
```

**Comment by SasaKaranovic** [comment] 2024-01-17 05:12
Thanks for quick reply @Famku 
It looks like the `vu1demo_config.yaml` is getting corrupted.

Can you try following steps:
- Close VU1 Demo app
- Remove `vu1demo_config.yaml` completely
- Start VU1 Demo app

Does the `vu1demo_config.yaml` look valid (feel free to paste it here again)?

**Comment by Famku** [comment] 2024-01-17 05:19
I already did that and did it again.

Same behaviour.

I also tried to set this file to write-protected after I set my settings, but the app did not start.

**Comment by SasaKaranovic** [comment] 2024-01-17 05:23
Thank you. I'll look into this.

FYI setting the file as write-protected would (most likely) prevent the app from starting and working properly because it relies on that file to read/write it's configuration.

**Comment by SasaKaranovic** [comment] 2024-01-17 05:30
@Famku So sorry to bug you so much. But would it be possible to post a screenshot of the VU1 Demo app you are using?

Also what OS are you using and are you running the VU1 Demo app as the administrator?

Thank you in advance!

**Comment by Famku** [comment] 2024-01-17 05:35
Windows11, running app as administrator

<img width="600" alt="image" src="https://github.com/SasaKaranovic/VU-Demo-App/assets/27890413/c7c0d518-9f21-4f85-848f-0fc25195747d">

**Comment by SasaKaranovic** [comment] 2024-01-17 06:56
@Famku I have created a new development branch and made small modification to the code that handles YAML file saving/loading.
Can you please try using the installer/zip from https://github.com/SasaKaranovic/VU-Demo-App/actions/runs/7551902229 and see if you get different result.

Please execute following step: 
- Close VU1-Demo App
- Remove `vu1demo_config.yaml`
- Install new VU1 Demo App using the installer from the link above
- Start VU1 Demo App
- Change metric settings for any dial
- Save dial config
- Close VU1 Demo app
- Re-start VU1 Demo app and check if configuration persists.

Thank you for helping with this issue! Much appreciated!

**Comment by Famku** [comment] 2024-01-17 07:03
Unfortunately the issue still exist with this version

**Comment by SirColeslaw** [comment] 2024-01-17 07:05
I did try this meanwhile, and unfortunately the problem stays the same with
me too.

**Comment by SasaKaranovic** [comment] 2024-01-17 07:08
Thanks for quick response.

@SirColeslaw Can you please post a screenshot of the VU1 Demo App?

I will continue to look into this. Unfortunately I can not reproduce this issue on the machines that I have so it makes debugging/tracing it a bit harder.

**Comment by SirColeslaw** [comment] 2024-01-17 07:20
![Screenshot 2024-01-17 081828](https://github.com/SasaKaranovic/VU-Demo-App/assets/45994510/03fb957e-8c06-4e1f-97bf-cefca728b6a6)

Here you go.

Btw, I have asked AIDA in the official forum for support for the VU1 dials in AIDA64. I am curious to see if I get a response.

**Comment by SasaKaranovic** [comment] 2024-01-18 02:37
@SirColeslaw @Famku there is a new build that tries to resolve this issue or at least help trace it.

Can you please try downloading the new installer from https://github.com/SasaKaranovic/VU-Demo-App/actions/runs/7564558122 and giving it a go. Thanks!

**Comment by Famku** [comment] 2024-01-18 10:00
same behavior, sorry

**Comment by SirColeslaw** [comment] 2024-01-18 11:38
Same for me

**Comment by SasaKaranovic** [comment] 2024-02-04 23:31
Hi @SirColeslaw @Famku 

Sorry about the delay, I had some stuff I had to deal with, but I'm back now.
Can you please check the latest build and see if the issue still persist -> https://github.com/SasaKaranovic/VU-Demo-App/actions/runs/7777497636

Please remove the Demo app AND the config file from `c:\Users\USERNAME\KaranovicResearch\VU1-DemoApp\vu1demo_config.yaml` before running the app.

Please let me know how it goes.

**Comment by SirColeslaw** [comment] 2024-02-05 08:07
Unfortunately, it still does not work, YAML and LOG file are attached.
[log20240205.zip](https://github.com/SasaKaranovic/VU-Demo-App/files/14162142/log20240205.zip)

**Comment by Famku** [comment] 2024-02-05 16:30
same here

**Comment by SasaKaranovic** [comment] 2024-02-06 04:43
@SirColeslaw @Famku Thanks for testing it out.

@SirColeslaw In the log file and the config file; it looks like the dials are detected and config file was saved properly.

When you get a chance, can you please try the following steps with the above mentioned version of the demo app:

1. Launch the VU Demo app
2. Select one of the dials from the list on the left (remember the Dial UID, we will need it again later)
3. For `Metric type` select `Load`
4. For `Selected Metric` select for example your CPU load (core or total, does not matter)
5. Click on `Save dial config` button (this is actually important step)
6. Verify that the `Metric` value (below `Dial Name` and `Dial UID`) changed to something like `CPU Total - Load ... - /amdcpu/0/load/0`
7. Exit the VU Demo app
8. Open the VU Demo app config file (located at `c:\Users\USERNAME\KaranovicResearch\VU1-DemoApp\vu1demo_config.yaml` )
9. There should be an entry with the Dial UID from step # 2 with `sensor_identifier` and value of something like `/amdcpu/0/load/0`
10. Start the VU Demo app again
11. From the list of dials on the left, select the same dial as in step # 2
12. Verify that the `Metric` value reads same as in step # 6

Thank you again for helping with tracing down this issue and please let me know if you have any issues.
Also if you still have issues after completing these steps, please feel free to attach the log file that should be located at `c:\Users\USERNAME\KaranovicResearch\VU1-DemoApp\logYYYYMMDD.txt`.
The YYYY, MM and DD are the year, month and day respectively, so please select the latest one. Or if not sure, feel free to upload all available logs.

**Comment by SirColeslaw** [comment] 2024-02-06 13:10
Wow, this time it worked, almost all settings were saved. And the settings now also appear in the YAML file. The only thing that is not saved is the color setting. After restarting the demo app, the light is off again and not white as I had set it.

EDIT: I was able to solve this with the colors via a rule. Now it looks like everything is working as it should. Do I have to do anything else to deactivate logging?

**Comment by SasaKaranovic** [comment] 2024-02-07 01:06
Great!

Note that you have to click on `Save dial config` every time you make changes to the dial. Otherwise they will be lost.
Also note that `Set color` feature is not stored in the config. Only the `Rules`

This branch will get merged and there is already a new version of the Demo app that is available for download from VU Dials website.

**Closed as completed by SasaKaranovic** 2024-02-07 01:06 UTC
